# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeSAC_WEEK12' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'FirebaseMessaging'

  # Pods for SeSAC_WEEK12

end
