# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SeSAC_WEEK07' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'IQKeyboardManagerSwift'

  # Pods for SeSAC_WEEK07

end
